[package]
name = "pabst"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[features]
rxp = ["rivlib"]

[dependencies]
las = { git = "https://github.com/gadomski/las-rs.git" }
rivlib = { git = "https://github.com/gadomski/rivlib-rs.git", optional = true }
