[package]
name = "pabst"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[features]
rxp-source = ["rivlib"]

[dependencies]
docopt = "0.6"
las = "0.3"
rivlib = { version="0.1", optional = true }
rustc-serialize = "0.3"
sdc = "0.1"
toml = "0.1"
